# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  mediaapi:
    image: mediaapi
    build:
      context: .
      dockerfile: MediaAPI/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5077:5077
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
